### PR TITLE
Fix compilation error with simd feature

### PR DESCRIPTION
**Pull request by jhorstmann**
# Which issue does this PR close?

Fixes a compilation error introduced in the last commit of PR #1161 

That commit was supposed to only add some comments, but I also removed one unneeded Result return type and did not try to compile with the simd feature afterwards.

cc @alamb

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you  @jhorstmann
  
All the tests passed on https://github.com/apache/arrow-rs/commit/68e5750b6165933aa2677e7a756e251fea22d622 

so that this is broken on master is surprising to me. Maybe it was a logical conflict 🤷

**Comment by alamb** [comment]
FWIW I think a new version of rust (1.58) was released which is likely breaking some of the CI tests on master

**Comment by jhorstmann** [comment]
Ah, I see there was also `multiply_scalar` introduced at nearly the same time, so it was the combination that failed.

**Comment by jhorstmann** [comment]
Looks like the test failures on master are due to an intentional change in rust: https://github.com/rust-lang/rust/commit/8731d4dfb479914a91f650f4f124528e332e8128#diff-363ad34c0858be71721f73b0880238813baf8f8b36ebbb494baa6b29103dd8d5

I don't know why we assert that exact formatting though. Also seems intentional because there is a range check in `fmt::Display for parquet::record::api`.
