### PR TITLE
fix main: parquet test compilation failure

### PR DESCRIPTION
**Pull request by Jefffrey**
audit failing

```sh
Crate:     quick-xml
Version:   0.39.3
Title:     Unbounded namespace-declaration allocation in `NsReader` enables memory-exhaustion denial of service
Date:      2026-06-29
ID:        RUSTSEC-2026-0195
URL:       https://rustsec.org/advisories/RUSTSEC-2026-0195
Severity:  7.5 (high)
Solution:  Upgrade to >=0.41.0
```

parquet test failing

```sh
error[E0061]: this function takes 6 arguments but 5 arguments were supplied
   --> parquet/src/arrow/arrow_reader/read_plan.rs:544:20
    |
544 |         let leaf = make_int32_page_reader(&data, &levels, &levels, 0, 0);
    |                    ^^^^^^^^^^^^^^^^^^^^^^------------------------------- argument #6 of type `Option<i16>` is missing
    |
note: function defined here
   --> parquet/src/arrow/array_reader/test_util.rs:102:8
    |
102 | pub fn make_int32_page_reader(
    |        ^^^^^^^^^^^^^^^^^^^^^^
...
108 |     padding_threshold: Option<i16>,
    |     ------------------------------
help: provide the argument
    |
544 |         let leaf = make_int32_page_reader(&data, &levels, &levels, 0, 0, /* Option<i16> */);
    |                                                                        +++++++++++++++++++

error[E0061]: this function takes 6 arguments but 5 arguments were supplied
   --> parquet/src/arrow/arrow_reader/read_plan.rs:550:29
    |
550 |         let struct_reader = StructArrayReader::new(struct_type, vec![leaf], 0, 0, false);
    |                             ^^^^^^^^^^^^^^^^^^^^^^-------------------------------------- argument #6 of type `Option<i16>` is missing
    |
note: associated function defined here
   --> parquet/src/arrow/array_reader/struct_array.rs:42:12
    |
 42 |     pub fn new(
    |            ^^^
...
 48 |         padding_threshold: Option<i16>,
    |         ------------------------------
help: provide the argument
    |
550 |         let struct_reader = StructArrayReader::new(struct_type, vec![leaf], 0, 0, false, /* Option<i16> */);
    |                                                                                        +++++++++++++++++++
```

### CODE REVIEW

**Comment by Jefffrey** [comment]
hm i guess object store needs to bump for quick-xml 🤔 

- https://github.com/apache/arrow-rs-object-store/pull/785

**Comment by alamb** [comment]
Thank you

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
QuickXML looks like we will need to wait for the object store release

**Comment by alamb** [comment]
PR to fix audit failure: https://github.com/apache/arrow-rs/pull/10267

**Comment by alamb** [comment]
The test failure is likely due to a logical conflict introduced by https://github.com/apache/arrow-rs/pull/9848

**Comment by HippoBaro** [comment]
Thanks @alamb and @Jefffrey 🙇
