### PR TITLE
Add tests for building applications using arrow with different feature flags

### LINKED ISSUE #529: master fails to compile with `default-features=false`
**Describe the bug**
Creating a new project with this `Cargo.toml` fails to compile:

```
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = {git = "https://github.com/apache/arrow-rs", rev = "80a57be3215ed7210971a501b10664cadfd59bea", default-features=false}
``` 

Output:

```
error[E0432]: unresolved import `rand::prelude::StdRng`
  --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/bench_util.rs:27:5
   |
27 |     prelude::StdRng,
   |     ^^^^^^^^^^^^^^^ no `StdRng` in `prelude`

error[E0432]: unresolved import `rand::rngs::StdRng`
  --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/test_util.rs:20:12
   |
20 | use rand::{rngs::StdRng, Rng, SeedableRng};
   |            ^^^^^^^^^^^^ no `StdRng` in `rngs`

error[E0308]: mismatched types
   --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/bench_util.rs:102:35
    |
94  | pub fn create_string_array<Offset: StringOffsetSizeTrait>(
    |                            ------ this type parameter
...
102 |             if rng.gen::<f32>() < null_density {
    |                                   ^^^^^^^^^^^^ expected type parameter `Offset`, found `f32`
    |
    = note: expected type parameter `Offset`
                         found type `f32`

error[E0308]: mismatched types
   --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/bench_util.rs:123:35
    |
114 | pub fn create_binary_array<Offset: BinaryOffsetSizeTrait>(
    |                            ------ this type parameter
...
123 |             if rng.gen::<f32>() < null_density {
    |                                   ^^^^^^^^^^^^ expected type parameter `Offset`, found `f32`
    |
    = note: expected type parameter `Offset`
                         found type `f32`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `arrow`
```

This is introduced in 80a57be3215ed7210971a501b10664cadfd59bea /  #488

There are quite often feature tag related bugs that could be prevented if we'd run [cargo hack](https://github.com/taiki-e/cargo-hack) in CI. 

Would you be willing to accept a PR that adds those checks? @alamb @jorgecarleitao @Dandandan @jhorstmann @nevi-me

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?
Re: https://github.com/apache/arrow-rs/issues/529

# Rationale for this change
 The current CI test ([here](https://github.com/apache/arrow-rs/blob/master/.github/workflows/rust.yml#L371)) to ensure arrow builds with various feature flags did not catch #529. This is because it is run in the context of the overall workspace which does not behave the same way as when arrow is used as a dependency

This PR contains the test strategy I propose to use for testing that arrow properly builds with different options. I plan a follow on PR that actually fixed #529

# What changes are included in this PR?

This PR contains the test strategy I propose to use for testing that arrow properly builds with different options. I plan a follow on PR that actually fixed #529

# Changes
1. Create actual projects that specify `arrow` as a dependency with various flags
2. Try to build that project in CI

Here is an example of the test running on CI: https://github.com/apache/arrow-rs/runs/3032269357?check_suite_focus=true (it is quite fast to check the projects)

You easily run these builds locally:
```shell
cd arrow/test/dependency/no-features
cargo check
```

I am sure there is some clever tool somewhere that claims to solve this problem (perhaps `cargo hack`? as suggested by @ritchie46). However, I chose to do it explicitly here because:
1. It is as close as possible to how an actual user will build their app with arrow
2. I can audit how it works without having to review projects and asses how mature / stable they are

# Are there any user-facing changes?

no

### CODE REVIEW

File: arrow/test/dependency/default-features/Cargo.toml [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+version = "0.1.0"
+edition = "2018"
+
+# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
+
+[dependencies]
+arrow = { path = "../../../../arrow", version = "5.0.0-SNAPSHOT" }
+
+# Workaround for https://github.com/apache/arrow-rs/issues/529
+rand = { version = "0.8" }
```
Comment (alamb) [inline arrow/test/dependency/default-features/Cargo.toml:30]: When this line is removed the test fails. I will remove it with the fix for https://github.com/apache/arrow-rs/issues/529

File: arrow/test/dependency/no-default-features/Cargo.toml [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
+
+[dependencies]
+arrow = { path = "../../../../arrow", version = "5.0.0-SNAPSHOT", default-features = false }
+
+# Workaround for https://github.com/apache/arrow-rs/issues/529
+rand = { version = "0.8" }
+
+[workspace]
```
Comment (nevi-me) [inline arrow/test/dependency/no-default-features/Cargo.toml:32]: stray line?

File: .github/workflows/rust.yml [hunk 3]
```diff
@@ -357,15 +353,22 @@ jobs:
...
           rustup toolchain install ${{ matrix.rust }}
           rustup override set ${{ matrix.rust }}
           rustup component add rustfmt
-      - name: Build arrow crate
+      - name: Build with default features
         run: |
           export CARGO_HOME="/github/home/.cargo"
           export CARGO_TARGET_DIR="/github/home/target"
-          cd arrow
-          cargo check --all-targets --no-default-features
```
Comment (nevi-me) [inline .github/workflows/rust.yml:371]: Could this be what was missing ito catching other feature types? That we weren't running `cargo check --all-targets --features simd,...`

**Review by nevi-me — APPROVED** [review]
I think this strategy is sound, LGTM

File: arrow/test/dependency/no-default-features/Cargo.toml (hunk 2 above)
Comment (alamb) [reply arrow/test/dependency/no-default-features/Cargo.toml:32]: Actually, this is required (you get a cargo build error without it). Somehow this signals to cargo that this project is not part of the workspace rooted at `arrow-rs/Cargo.toml`

File: .github/workflows/rust.yml (hunk 3 above)
Comment (alamb) [reply .github/workflows/rust.yml:371]: I think the reason CI isn't catching issues with feature flags is due to the cargo semantics of a `workspace` -- where Cargo tries to calculate the dependency needs of the workspace as a whole. Since we have some crates in the workspace (like `arrow-flight`) that bring in additional dependencies, these additional dependencies can obscure build problems with other crates (like `arrow`) when used alone
