### ISSUE TITLE
Bumping version gives compilation error (arrow-array)

### ISSUE THREAD

**Issue by bmmeijers** [apache/arrow-rs#3525]
**Which part is this question about**

When bumping my dependencies from v26 to a higher version, I get a compile time error on my project:

```
error[E0432]: unresolved import `num::complex::ComplexFloat`
  --> /home/martijn/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-array-27.0.0/src/arithmetic.rs:21:5
   |
21 | use num::complex::ComplexFloat;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ComplexFloat` in `complex`

error[E0599]: no method named `powi` found for struct `f16` in the current scope
   --> /home/martijn/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-array-27.0.0/src/arithmetic.rs:329:25
    |
329 |                 Ok(self.powi(exp as i32))
    |                         ^^^^ method not found in `f16`
...
358 | native_type_float_op!(f16, f16::ONE, f16::ZERO);
    | ----------------------------------------------- in this macro invocation
    |
    = help: items from traits can only be used if the trait is in scope
    = note: this error originates in the macro `native_type_float_op` (in Nightly builds, run with -Z macro-backtrace for more info)
help: the following traits are implemented but not in scope; perhaps add a `use` for one of them:
    |
18  | use num::Float;
    |
18  | use num::traits::float::FloatCore;
    |
18  | use num::traits::real::Real;
    |

error[E0599]: no method named `powi` found for struct `f16` in the current scope
   --> /home/martijn/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-array-27.0.0/src/arithmetic.rs:334:22
    |
334 |                 self.powi(exp as i32)
    |                      ^^^^ method not found in `f16`
...
358 | native_type_float_op!(f16, f16::ONE, f16::ZERO);
    | ----------------------------------------------- in this macro invocation
    |
    = help: items from traits can only be used if the trait is in scope
    = note: this error originates in the macro `native_type_float_op` (in Nightly builds, run with -Z macro-backtrace for more info)
help: the following traits are implemented but not in scope; perhaps add a `use` for one of them:
    |
18  | use num::Float;
    |
18  | use num::traits::float::FloatCore;
    |
18  | use num::traits::real::Real;
    |
```

**Describe your question**

Is this a problem with the arrow / parquet dependencies or do I need to do something on my rust environment?

**Additional context**

v.26 of arrow and parquet libs works, when going higher to v27 -- v30.0.1give all same compilation error on compiling arrow-array.

**Comment by tustvold** [comment]
Is there a lockfile present, that is pinning to an older version of num?

**Comment by bmmeijers** [comment]
Yeah, there is a dependency on num-bigint / num-traits that I did not bump.

**Comment by bmmeijers** [comment]
Thanks, running `cargo update` solved it for me.
