### ISSUE TITLE
master fails to compile with `default-features=false`

### ISSUE THREAD

**Issue by ritchie46** [apache/arrow-rs#529]
**Describe the bug**
Creating a new project with this `Cargo.toml` fails to compile:

```
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = {git = "https://github.com/apache/arrow-rs", rev = "80a57be3215ed7210971a501b10664cadfd59bea", default-features=false}
``` 

Output:

```
error[E0432]: unresolved import `rand::prelude::StdRng`
  --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/bench_util.rs:27:5
   |
27 |     prelude::StdRng,
   |     ^^^^^^^^^^^^^^^ no `StdRng` in `prelude`

error[E0432]: unresolved import `rand::rngs::StdRng`
  --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/test_util.rs:20:12
   |
20 | use rand::{rngs::StdRng, Rng, SeedableRng};
   |            ^^^^^^^^^^^^ no `StdRng` in `rngs`

error[E0308]: mismatched types
   --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/bench_util.rs:102:35
    |
94  | pub fn create_string_array<Offset: StringOffsetSizeTrait>(
    |                            ------ this type parameter
...
102 |             if rng.gen::<f32>() < null_density {
    |                                   ^^^^^^^^^^^^ expected type parameter `Offset`, found `f32`
    |
    = note: expected type parameter `Offset`
                         found type `f32`

error[E0308]: mismatched types
   --> /home/ritchie46/.cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/80a57be/arrow/src/util/bench_util.rs:123:35
    |
114 | pub fn create_binary_array<Offset: BinaryOffsetSizeTrait>(
    |                            ------ this type parameter
...
123 |             if rng.gen::<f32>() < null_density {
    |                                   ^^^^^^^^^^^^ expected type parameter `Offset`, found `f32`
    |
    = note: expected type parameter `Offset`
                         found type `f32`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `arrow`
```

This is introduced in 80a57be3215ed7210971a501b10664cadfd59bea /  #488

There are quite often feature tag related bugs that could be prevented if we'd run [cargo hack](https://github.com/taiki-e/cargo-hack) in CI. 

Would you be willing to accept a PR that adds those checks? @alamb @jorgecarleitao @Dandandan @jhorstmann @nevi-me

**Comment by alamb** [comment]
For anyone finding this ticket, a workaround is to add the following to your Cargo dependencies:
```
# ensure we get the std version of rand so arrow builds without default features
rand = { version = "0.8" }
```

**Comment by alamb** [comment]
@ritchie46  I am not sure about cargo-hack -- would the idea be to check every combination of arguments?

Note we supposedly already have a CI check for `--no-default-features` here:
https://github.com/apache/arrow-rs/blob/master/.github/workflows/rust.yml#L116

But clearly that did not catch this regression

**Comment by ritchie46** [comment]
> @ritchie46 I am not sure about cargo-hack -- would the idea be to check every combination of arguments?

Indeed. Running `cargo hack check --each-feature --no-dev-deps` would run a `cargo check` on all possible feature combinations.

**Comment by joshuataylor** [comment]
I'm also getting this when using:
```
arrow = { git = "https://github.com/apache/arrow-rs" }
```

Adding rand does not fix this.

**Comment by alamb** [comment]
I am starting to work on this one

**Comment by alamb** [comment]
github got a little excited and closed this prior to the fix actually being merged
