### PR TITLE
object_store: fix failing doctest with default features

### LINKED ISSUE #5025: Object Store Doctest Failure with Default Features
**Describe the bug**

Running `cargo test` on the object_store crate result in a failing doctest

```
---- src/lib.rs - (line 105) stdout ----
error[E0432]: unresolved import `object_store::aws`
 --> src/lib.rs:109:19
  |
7 | use object_store::aws::{AmazonS3, AmazonS3Builder};
  |                   ^^^ could not find `aws` in `object_store`
```

This was introduced in #4978 and not caught by CI as we only test with all features

**To Reproduce**

**Expected behavior**

**Additional context**

https://github.com/apache/arrow-rs/pull/5024 worked around this for the purposes of release verification, and is also generally a more correct for the verification scripts to be doing.

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5025

# Rationale for this change
 

# What changes are included in this PR?

Fix doctest to be encapsulated within block which depends on aws feature

Add block to doctest

# Are there any user-facing changes?

### CODE REVIEW

File: object_store/Cargo.toml [hunk 1]
```diff
@@ -67,10 +67,10 @@ http = ["cloud"]
 tls-webpki-roots = ["reqwest?/rustls-tls-webpki-roots"]
 
 [dev-dependencies] # In alphabetical order
-tempfile = "3.1.0"
 futures-test = "0.3"
-rand = "0.8"
 hyper = { version = "0.14.24", features = ["server"] }
+rand = "0.8"
+tempfile = "3.1.0"
```
Comment (Jefffrey) [inline object_store/Cargo.toml:73]: Just reordering to respect the comment about order

**Comment by tustvold** [comment]
> Worth introducing something like cargo hack

I played with this a while back, the problem is testing all the feature combinations takes a very long time
