### ISSUE TITLE
Object Store Doctest Failure with Default Features

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5025]
**Describe the bug**

Running `cargo test` on the object_store crate result in a failing doctest

```
---- src/lib.rs - (line 105) stdout ----
error[E0432]: unresolved import `object_store::aws`
 --> src/lib.rs:109:19
  |
7 | use object_store::aws::{AmazonS3, AmazonS3Builder};
  |                   ^^^ could not find `aws` in `object_store`
```

This was introduced in #4978 and not caught by CI as we only test with all features

**To Reproduce**

**Expected behavior**

**Additional context**

https://github.com/apache/arrow-rs/pull/5024 worked around this for the purposes of release verification, and is also generally a more correct for the verification scripts to be doing.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5161

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5025](https://github.com/apache/arrow-rs/issues/5025)
